spring.application.name=wiki
server.address=0.0.0.0
server.port=8080

spring.datasource.url=jdbc:postgresql://postgres:5432/wiki
spring.datasource.username=postgres
spring.datasource.password=javeriana

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true